name: unified_dbt_project
version: 1.0
config-version: 2

profile: unified_project

model-paths: ["models"]

target-path: "target"
clean-targets: ["target"]

models:
  unified_dbt_project:
    reports:
      preprod:
        +schema: "preprod_schema"
        +enabled: "{{ target.name == 'preprod' }}"
      prod:
        +schema: "prod_schema"
        +enabled: "{{ target.name == 'prod' }}"
    shared:
      +enabled: true
